### ISSUE TITLE
Preheat build plate uses wrong temperature

### ISSUE THREAD

**Issue by dxgldotorg** [fieldOfView/Cura-OctoPrintPlugin#171]
I have my Cura settings with a higher initial temperature for the build plate to help the first layer stick better but drop my temperature after the first layer.  The preheat button, instead of using the "Build Plate Temperature Initial Layer" setting, uses the "Build Plate Temperature" setting to preheat.

**Comment by fieldOfView** [comment]
This would need to be fixed in Cura, not in this plugin. 

It would not be a hard thing to fix, but I am not 100% sure if it should be done. It would cause a lot of confusion for printers where the initial build plate temperature is always 5 degrees higher than the normal build plate temperature. In those cases, users will wonder why Cura uses a different temperature for preheating than what they have entered.

As a workaround, you can always change the value that will be used for preheating.

**Comment by dxgldotorg** [comment]
Thanks; I was thinking about reporting it in Cura but figured it was the addon's issue.
