### ISSUE TITLE
Can't enable PSU Control

### ISSUE THREAD

**Issue by TScalzott** [fieldOfView/Cura-OctoPrintPlugin#191]
I have Octopi running with PSU Control plugin, which functions well from OctoPrint.  
In Cura, the option to "turn on printer with..." is grayed out.

Nevermind...you need the start printing option to be selected.

**Comment by yasars** [comment]
same too any fixx?

**Comment by fieldOfView** [comment]
@yasars, this issue was closed by the user, because he figured out the "fix" by himself. You need to have the option the start printing selected. If you don't want to start printing after upload, then why would the printer need to be turned on?

If that does not fix your issue, please open a new issue with more details about what your problem is. Perhaps add a screenshot. You may also want to have a look at https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/232

**Comment by yasars** [comment]
thats help thank you :) 👍
