### ISSUE TITLE
CURA 4.8 launch previous print after turning on the printer

### ISSUE THREAD

**Issue by Elidji** [fieldOfView/Cura-OctoPrintPlugin#222]
Hello,

I have a problem since I installed the TP-Link plugin.

When I slice a file and then select print with octoprint the printer start normally and octoprint connect to it but then it launches the previous file I printed instead of the new one.
I don't know what is causing this.

How to reproduce :
  - Let a print finish and the printer shut down with the tp link.
  - Slice a file in CURA.
  - Select Print with octoprint.
  - Verify in Octoprint, the file selected is the old one not the new one.

I use a Creality CR-6.

**Comment by jonjon09** [comment]
Same issue here. Creality Ender 3 pro.
Unrelated issue but also seems to be due to this plugin - there is some sort of memory leak for me. When I enable it and leave cura open, my computer slows to a crawl with 99% of my RAM used (I have 16GB, only around 50% when not being bogged down by this bug). Unfortunate because I love the convenience of the plugin but not with these 2 major issues.

**Comment by fieldOfView** [comment]
> Unrelated issue but also seems to be due to this plugin

Please open a new issue for that, or I will loose track of the issue and the chance of it getting fixed will be low.

**Comment by fieldOfView** [comment]
> When I slice a file and then select print with octoprint the printer start normally and octoprint connect to it but then it launches the previous file I printed instead of the new one.

I need a set of log files reproducing this issue: both the Cura.log which can be found via Help -> Show configuration folder in Cura, and the octoprint.log which can be found via the settings in the OctoPrint web interface. Please upload them somewhere and post a link here.

**Comment by fieldOfView** [comment]
I can't help you without log files.
