### ISSUE TITLE
no connection possilbe over https

### ISSUE THREAD

**Issue by McSlinplay** [fieldOfView/Cura-OctoPrintPlugin#231]
Hello,
I just wanted to connect to my printer over the internet using https but the configure connection dialog does not allow adding https:// to the url. Unfortunately I cannot do this with specifying a different port due to how my reverse proxy is configured.
It would be great I this is changed.
If more information about this is needed I will add it.
Kind regards

**Comment by fieldOfView** [comment]
I'm not sure if you closed this because you found the solution, or by accident.

The solution is to "Add" a connection manually instead of using the discovered instances. Since OctoPrint does not know that there is a https proxy, it only advertises http. With manually added instances, you can specify to use https (and basic authentication) via the reverse proxy options that are collapsed by default in the "Add" dialog.
